### ISSUE TITLE
Does this work with git-subtree?

### ISSUE THREAD

**Issue by jasonkarns** [s0/git-publish-subdir-action#8]
Will this action work with subdirectories already pushed (and rejoined using --rejoin) to other repos using `git subtree split/push`? I have an existing monorepo with subdirs that have their own subtree-maintained repositories. But I want to be sure that this action would maintain the history as created by git-subtree.

**Comment by equiman** [comment]
I don't know how it works internally, but I tested it and I see al my previous commits.

https://github.com/deinsoftware/hardhat/commits/mac
https://github.com/deinsoftware/hardhat/commits/win

**Comment by s0** [comment]
I haven't tested it yet, but it should do? All it does is add an additional commit to the current HEAD of target branch (unless you use `SQUASH_HISTORY`).

That being said, it does copy files to the root of the target branch, so if you're trying to target a specific subdirectory on the target branch, all other files / folders will be deleted.

Could you shad a bit more light as to your use-case, or even better provide some example repos? I've implemented unit-tests now so once I have a better understanding we can add some tests to ensure the behaviour is as desired.

**Comment by jasonkarns** [comment]
git-subtree is built specifically to allow a directory in one repo to map to the root of another repo. (Which seems like exactly the use case this action is built for.) The benefits of git subtree is that changes can be pushed in either direction, and the git history is preserved in both directions.

My initial use-case was to support a monorepo of GitHub Actions (since the current implementation of Actions requires that each action have its own repo, and be at the root of that repo). I ended up just using git-subtree directly to accomplish this. 

monorepo: https://github.com/nodenv/actions

Instead of using git-publish-subdir-action, I essentially hand-rolled it with git-subtree: 
https://github.com/nodenv/actions/blob/090ac792fdfa5c3c978036bf636039438b7ab972/.github/workflows/sync.yml#L18-L22

**Comment by s0** [comment]
Ah okay cool, i see what you mean.

I hadn't actually built this action with that in mind, i'd mostly been wanting it to push build artifacts / generated files after some build step (e.g. publishing a gatsby site to github pages). So notably, there's no guarantee that the files people are interested in pushing are actually checked-in to git, so using git-subtree wouldn't work for all use-cases.

For the use case you describe, i've previously used submodules rather than git-subtree, though i can see the appeal of subtree over submodules here.

I'll have to give it some thought, i'm not sure whether creating an action really provides much benefit over specifying the subtree commands directly in an actions file like you have. Additionally some thought would need to be given about what to do when the target branch has changed.. do we merge changes back in? etc... I welcome any input you have on that.

Also one further question, i notice you don't specify any auth in your actions files, that surprises me somewhat as I didn't think you could have cross-repo pushing without some kind of token / deploy key. It may be possible i could simplify this action if that's possible, how does the auth work for your linked workflow?

**Comment by jasonkarns** [comment]
> I'll have to give it some thought, i'm not sure whether creating an action really provides much benefit over specifying the subtree commands directly in an actions file like you have.

Yep, I think the primary benefit would just be a more declarative configuration. A single-line "uses: action" declaration is more clear than a few lines of obscure and interpolated shell commands 😸 . But I agree, the benefit is slight.




> how does the auth work for your linked workflow?

The checkout action (as of v2), persists the auth token into the local git configuration. So the repo token configured [here](https://github.com/nodenv/actions/blob/090ac792fdfa5c3c978036bf636039438b7ab972/.github/workflows/sync.yml#L17) is the same one used for all subsequent git operations. Instead of using the default token (which has read access to its "own" repo) we use a token that has write access on the remotes.

**Comment by s0** [comment]
> The checkout action (as of v2), persists the auth token into the local git configuration. So the repo token configured [here](https://github.com/nodenv/actions/blob/090ac792fdfa5c3c978036bf636039438b7ab972/.github/workflows/sync.yml#L17) is the same one used for all subsequent git operations. Instead of using the default generated token (which has read access to its "own" repo) we use a token that has write access on the remotes.

Ah cool, good to know! That's probably not particularly useful for this action then given that it uses SSH + deploy keys rather than HTTP and access tokens. :)

**Comment by jasonkarns** [comment]
Thanks for the discussion! I'm going to close this for now, since it seems that _generally_ the use cases don't align exactly. It would be cool to see an implementation that allowed users to "opt-in" to 100% subtree compatible usage. But I suspect the cost/benefit doesn't make the feature quite worth it.

**Comment by s0** [comment]
Makes sense, we agree here, thanks! :)
